(function() {var implementors = {};
implementors["channel_protocol"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"cbor_protocol/enum.ProtocolError.html\" title=\"enum cbor_protocol::ProtocolError\">ProtocolError</a>&gt; for <a class=\"enum\" href=\"channel_protocol/enum.ProtocolError.html\" title=\"enum channel_protocol::ProtocolError\">ProtocolError</a>",synthetic:false,types:["channel_protocol::error::ProtocolError"]},];
implementors["comms_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u16.html\">u16</a>&gt; for <a class=\"enum\" href=\"comms_service/enum.PayloadType.html\" title=\"enum comms_service::PayloadType\">PayloadType</a>",synthetic:false,types:["comms_service::packet::PayloadType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"comms_service/enum.PayloadType.html\" title=\"enum comms_service::PayloadType\">PayloadType</a>&gt; for <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u16.html\">u16</a>",synthetic:false,types:[]},];
implementors["eps_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"eps_api/enum.EpsError.html\" title=\"enum eps_api::EpsError\">EpsError</a>",synthetic:false,types:["eps_api::EpsError"]},];
implementors["file_protocol"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"cbor_protocol/enum.ProtocolError.html\" title=\"enum cbor_protocol::ProtocolError\">ProtocolError</a>&gt; for <a class=\"enum\" href=\"file_protocol/enum.ProtocolError.html\" title=\"enum file_protocol::ProtocolError\">ProtocolError</a>",synthetic:false,types:["file_protocol::error::ProtocolError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;Error&gt; for <a class=\"enum\" href=\"file_protocol/enum.ProtocolError.html\" title=\"enum file_protocol::ProtocolError\">ProtocolError</a>",synthetic:false,types:["file_protocol::error::ProtocolError"]},];
implementors["mai400_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"mai400_api/enum.UartError.html\" title=\"enum mai400_api::UartError\">UartError</a>&gt; for <a class=\"enum\" href=\"mai400_api/enum.MAIError.html\" title=\"enum mai400_api::MAIError\">MAIError</a>",synthetic:false,types:["mai400_api::mai400::MAIError"]},];
implementors["mai400_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt; for <a class=\"enum\" href=\"mai400_service/enum.Mode.html\" title=\"enum mai400_service::Mode\">Mode</a>",synthetic:false,types:["mai400_service::objects::Mode"]},];
implementors["novatel_oem6_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"enum\" href=\"novatel_oem6_api/enum.ResponseID.html\" title=\"enum novatel_oem6_api::ResponseID\">ResponseID</a>",synthetic:false,types:["novatel_oem6_api::messages::commands::ResponseID"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u16.html\">u16</a>&gt; for <a class=\"enum\" href=\"novatel_oem6_api/enum.MessageID.html\" title=\"enum novatel_oem6_api::MessageID\">MessageID</a>",synthetic:false,types:["novatel_oem6_api::messages::MessageID"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"novatel_oem6_api/enum.UartError.html\" title=\"enum novatel_oem6_api::UartError\">UartError</a>&gt; for <a class=\"enum\" href=\"novatel_oem6_api/enum.OEMError.html\" title=\"enum novatel_oem6_api::OEMError\">OEMError</a>",synthetic:false,types:["novatel_oem6_api::oem6::OEMError"]},];
implementors["novatel_oem6_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"enum\" href=\"novatel_oem6_service/enum.SolutionStatus.html\" title=\"enum novatel_oem6_service::SolutionStatus\">SolutionStatus</a>",synthetic:false,types:["novatel_oem6_service::objects::SolutionStatus"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u32.html\">u32</a>&gt; for <a class=\"enum\" href=\"novatel_oem6_service/enum.PosVelType.html\" title=\"enum novatel_oem6_service::PosVelType\">PosVelType</a>",synthetic:false,types:["novatel_oem6_service::objects::PosVelType"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>&gt; for <a class=\"enum\" href=\"novatel_oem6_service/enum.RefTimeStatus.html\" title=\"enum novatel_oem6_service::RefTimeStatus\">RefTimeStatus</a>",synthetic:false,types:["novatel_oem6_service::objects::RefTimeStatus"]},];
implementors["rust_uart"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">Error</a>&gt; for <a class=\"enum\" href=\"rust_uart/enum.UartError.html\" title=\"enum rust_uart::UartError\">UartError</a>",synthetic:false,types:["rust_uart::error::UartError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;Error&gt; for <a class=\"enum\" href=\"rust_uart/enum.UartError.html\" title=\"enum rust_uart::UartError\">UartError</a>",synthetic:false,types:["rust_uart::error::UartError"]},];
implementors["shell_protocol"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"cbor_protocol/enum.ProtocolError.html\" title=\"enum cbor_protocol::ProtocolError\">ProtocolError</a>&gt; for <a class=\"enum\" href=\"shell_protocol/error/enum.ProtocolError.html\" title=\"enum shell_protocol::error::ProtocolError\">ProtocolError</a>",synthetic:false,types:["shell_protocol::error::ProtocolError"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"channel_protocol/error/enum.ProtocolError.html\" title=\"enum channel_protocol::error::ProtocolError\">ProtocolError</a>&gt; for <a class=\"enum\" href=\"shell_protocol/error/enum.ProtocolError.html\" title=\"enum shell_protocol::error::ProtocolError\">ProtocolError</a>",synthetic:false,types:["shell_protocol::error::ProtocolError"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()