(function() {var implementors = {};
implementors["clyde_3g_eps_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"clyde_3g_eps_api/struct.StatusCode.html\" title=\"struct clyde_3g_eps_api::StatusCode\">StatusCode</a>",synthetic:false,types:["clyde_3g_eps_api::commands::board_status::StatusCode"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"clyde_3g_eps_api/DaughterboardTelemetry/enum.Type.html\" title=\"enum clyde_3g_eps_api::DaughterboardTelemetry::Type\">Type</a>",synthetic:false,types:["clyde_3g_eps_api::telemetry::daughterboard::Type"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"clyde_3g_eps_api/MotherboardTelemetry/enum.Type.html\" title=\"enum clyde_3g_eps_api::MotherboardTelemetry::Type\">Type</a>",synthetic:false,types:["clyde_3g_eps_api::telemetry::motherboard::Type"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"clyde_3g_eps_api/ResetTelemetry/enum.Type.html\" title=\"enum clyde_3g_eps_api::ResetTelemetry::Type\">Type</a>",synthetic:false,types:["clyde_3g_eps_api::telemetry::reset::Type"]},];
implementors["clyde_3g_eps_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"clyde_3g_eps_service/models/subsystem/enum.Mutations.html\" title=\"enum clyde_3g_eps_service::models::subsystem::Mutations\">Mutations</a>",synthetic:false,types:["clyde_3g_eps_service::models::subsystem::Mutations"]},];
implementors["gomspace_p31u_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"gomspace_p31u_service/enum.AckCommand.html\" title=\"enum gomspace_p31u_service::AckCommand\">AckCommand</a>",synthetic:false,types:["gomspace_p31u_service::objects::AckCommand"]},];
implementors["isis_ants_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"isis_ants_service/enum.AckCommand.html\" title=\"enum isis_ants_service::AckCommand\">AckCommand</a>",synthetic:false,types:["isis_ants_service::objects::AckCommand"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"isis_ants_service/enum.ConfigureController.html\" title=\"enum isis_ants_service::ConfigureController\">ConfigureController</a>",synthetic:false,types:["isis_ants_service::objects::ConfigureController"]},];
implementors["isis_iobc_supervisor"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"isis_iobc_supervisor/struct.SupervisorEnableStatus.html\" title=\"struct isis_iobc_supervisor::SupervisorEnableStatus\">SupervisorEnableStatus</a>",synthetic:false,types:["isis_iobc_supervisor::SupervisorEnableStatus"]},];
implementors["kubos_telemetry_db"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"kubos_telemetry_db/telemetry/struct.table.html\" title=\"struct kubos_telemetry_db::telemetry::table\">table</a>",synthetic:false,types:["kubos_telemetry_db::telemetry::table"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"kubos_telemetry_db/telemetry/columns/struct.star.html\" title=\"struct kubos_telemetry_db::telemetry::columns::star\">star</a>",synthetic:false,types:["kubos_telemetry_db::telemetry::columns::star"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"kubos_telemetry_db/telemetry/columns/struct.timestamp.html\" title=\"struct kubos_telemetry_db::telemetry::columns::timestamp\">timestamp</a>",synthetic:false,types:["kubos_telemetry_db::telemetry::columns::timestamp"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"kubos_telemetry_db/telemetry/columns/struct.subsystem.html\" title=\"struct kubos_telemetry_db::telemetry::columns::subsystem\">subsystem</a>",synthetic:false,types:["kubos_telemetry_db::telemetry::columns::subsystem"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"kubos_telemetry_db/telemetry/columns/struct.parameter.html\" title=\"struct kubos_telemetry_db::telemetry::columns::parameter\">parameter</a>",synthetic:false,types:["kubos_telemetry_db::telemetry::columns::parameter"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"kubos_telemetry_db/telemetry/columns/struct.value.html\" title=\"struct kubos_telemetry_db::telemetry::columns::value\">value</a>",synthetic:false,types:["kubos_telemetry_db::telemetry::columns::value"]},];
implementors["mai400_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"mai400_api/struct.ThermopileFlags.html\" title=\"struct mai400_api::ThermopileFlags\">ThermopileFlags</a>",synthetic:false,types:["mai400_api::messages::rx::irehs::ThermopileFlags"]},];
implementors["mai400_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"mai400_service/enum.AckCommand.html\" title=\"enum mai400_service::AckCommand\">AckCommand</a>",synthetic:false,types:["mai400_service::objects::AckCommand"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"mai400_service/enum.Mode.html\" title=\"enum mai400_service::Mode\">Mode</a>",synthetic:false,types:["mai400_service::objects::Mode"]},];
implementors["novatel_oem6_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"novatel_oem6_api/enum.MessageID.html\" title=\"enum novatel_oem6_api::MessageID\">MessageID</a>",synthetic:false,types:["novatel_oem6_api::messages::MessageID"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"novatel_oem6_api/struct.ReceiverStatusFlags.html\" title=\"struct novatel_oem6_api::ReceiverStatusFlags\">ReceiverStatusFlags</a>",synthetic:false,types:["novatel_oem6_api::messages::ReceiverStatusFlags"]},];
implementors["novatel_oem6_service"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"enum\" href=\"novatel_oem6_service/enum.AckCommand.html\" title=\"enum novatel_oem6_service::AckCommand\">AckCommand</a>",synthetic:false,types:["novatel_oem6_service::objects::AckCommand"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()