(function() {var implementors = {};
implementors["clyde_3g_eps_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a>&lt;<a class=\"struct\" href=\"clyde_3g_eps_api/struct.StatusCode.html\" title=\"struct clyde_3g_eps_api::StatusCode\">StatusCode</a>&gt; for <a class=\"struct\" href=\"clyde_3g_eps_api/struct.StatusCode.html\" title=\"struct clyde_3g_eps_api::StatusCode\">StatusCode</a>",synthetic:false,types:["clyde_3g_eps_api::commands::board_status::StatusCode"]},];
implementors["kubos_telemetry_db"] = [{text:"impl&lt;Rhs&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a>&lt;Rhs&gt; for <a class=\"struct\" href=\"kubos_telemetry_db/telemetry/columns/struct.timestamp.html\" title=\"struct kubos_telemetry_db::telemetry::columns::timestamp\">timestamp</a> <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;Rhs: AsExpression&lt;&lt;&lt;<a class=\"struct\" href=\"kubos_telemetry_db/telemetry/columns/struct.timestamp.html\" title=\"struct kubos_telemetry_db::telemetry::columns::timestamp\">timestamp</a> as Expression&gt;::SqlType as Sub&gt;::Rhs&gt;,&nbsp;</span>",synthetic:false,types:["kubos_telemetry_db::telemetry::columns::timestamp"]},];
implementors["mai400_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a>&lt;<a class=\"struct\" href=\"mai400_api/struct.ThermopileFlags.html\" title=\"struct mai400_api::ThermopileFlags\">ThermopileFlags</a>&gt; for <a class=\"struct\" href=\"mai400_api/struct.ThermopileFlags.html\" title=\"struct mai400_api::ThermopileFlags\">ThermopileFlags</a>",synthetic:false,types:["mai400_api::messages::rx::irehs::ThermopileFlags"]},];
implementors["novatel_oem6_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/arith/trait.Sub.html\" title=\"trait core::ops::arith::Sub\">Sub</a>&lt;<a class=\"struct\" href=\"novatel_oem6_api/struct.ReceiverStatusFlags.html\" title=\"struct novatel_oem6_api::ReceiverStatusFlags\">ReceiverStatusFlags</a>&gt; for <a class=\"struct\" href=\"novatel_oem6_api/struct.ReceiverStatusFlags.html\" title=\"struct novatel_oem6_api::ReceiverStatusFlags\">ReceiverStatusFlags</a>",synthetic:false,types:["novatel_oem6_api::messages::ReceiverStatusFlags"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()